const test=require('node:test'), assert=require('node:assert/strict'), fs=require('fs'), vm=require('vm'),{webcrypto}=require('crypto');
const html=fs.readFileSync('public/index.html','utf8');
const start=html.indexOf('const uploadOcrCache = new Map();'),end=html.indexOf('async function handleFileUpload',start);
function setup(call){const calls=[];const c=vm.createContext({crypto:webcrypto,TextEncoder,Uint8Array,callClaude:async(...args)=>{calls.push(args);return call?call(...args):'가입 조건 원문';}});vm.runInContext(html.slice(start,end),c);return{c,calls};}
test('identical image OCR is paid once per session and uses bounded cheap model without retry',async()=>{const{c,calls}=setup();assert.equal(await c.extractTextFromImageBase64('same','image/jpeg'),'가입 조건 원문');await c.extractTextFromImageBase64('same','image/jpeg');assert.equal(calls.length,1);assert.equal(calls[0][2],0);assert.equal(calls[0][4],4096);assert.equal(calls[0][5],'claude-haiku-4-5-20251001');assert.equal(calls[0][6].rejectTruncated,true);await c.extractTextFromImageBase64('changed','image/jpeg');assert.equal(calls.length,2);});
test('failed or blank OCR cannot poison the cache and can be retried explicitly',async()=>{let n=0;const{c,calls}=setup(()=>++n===1?'':'완전한 원문');await assert.rejects(c.extractTextFromImageBase64('same','image/jpeg'),/비어/);assert.equal(await c.extractTextFromImageBase64('same','image/jpeg'),'완전한 원문');assert.equal(calls.length,2);});
function recoSetup(){const listeners={},nodes=new Map(),calls=[];let failSave=true;const node=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='recoSource'?'상품 원문':'',style:{},addEventListener:(event,fn)=>listeners[id]=fn});return nodes.get(id);};const c=vm.createContext({crypto:webcrypto,TextEncoder,Uint8Array,UploadEngine:require('../public/upload-engine'),document:{getElementById:node},alert(){},callClaude:async(...args)=>{calls.push(args);return JSON.stringify([{insurer:'A사',product_name:'상품',category:'암보험',reason:'원문에 있는 조건'}]);},apiPost:async()=>{if(failSave)throw Error('DB save failed');},refreshRecoList:async()=>{}});vm.runInContext(html.slice(start,end),c);const a=html.indexOf("document.getElementById('recoExtractBtn').addEventListener");const b=html.indexOf("document.getElementById('recoFormat').addEventListener",a);vm.runInContext(html.slice(a,b),c);return{run:listeners.recoExtractBtn,calls,node,allowSave:()=>failSave=false};}
test('newsletter DB failure preserves source; explicit retry reuses analysis without another paid call',async()=>{const h=recoSetup();await h.run();assert.equal(h.node('recoSource').value,'상품 원문');assert.equal(h.calls.length,1);h.allowSave();await h.run();assert.equal(h.calls.length,1);assert.equal(h.node('recoSource').value,'');assert.equal(h.calls[0][2],0);assert.equal(h.calls[0][5],'claude-haiku-4-5-20251001');});

test('text detector routes empty and corrupt pages to OCR but leaves readable Korean free',()=>{const e=require('../public/upload-engine');assert.equal(e.inspectText('보험 상품의 가입 조건과 지급 기준은 반드시 해당 약관에서 확인해 주세요. 3.10.5').needsOcr,false);assert.equal(e.inspectText('').needsOcr,true);assert.equal(e.inspectText('౸ݒਭਊ'.repeat(30)).needsOcr,true);const clean=e.inspectText('보장 조건과 약관을 확인해주세요. 충분한 한국어 설명과 예외 조건을 함께 확인합니다. ౸ݒ');assert.equal(clean.needsOcr,false);assert.ok(!clean.cleaned.includes('౸'));assert.match(clean.cleaned,/문자 깨짐/);});
test('more than ten documents are split without truncation or cross-company batches',()=>{const e=require('../public/upload-engine');const raw=Array.from({length:12},(_,i)=>`--- 회사${i}.pdf 추출 내용 (2페이지) ---\n[p.1]\n${('상품 조건 '+i+' ').repeat(900)}\n[p.2]\n예외 조건 ${i}\n`).join('\n');const batches=e.splitNewsletters(raw);assert.ok(batches.length>=12);assert.ok(batches.every(b=>b.text.length<=6000));for(let i=0;i<12;i++){assert.ok(batches.some(b=>b.name===`회사${i}.pdf`&&b.text.includes('예외 조건 '+i)));}assert.ok(batches.every(b=>(b.text.match(/--- 회사/g)||[]).length<=1));});
test('malformed JSON receives a clear error and empty non-product sections are valid',()=>{const e=require('../public/upload-engine');assert.throws(()=>e.parseItems('[{"reason":"unfinished'),/JSON/);assert.deepEqual(e.parseItems('[]'),[]);assert.throws(()=>e.parseItems('[{"reason":"only"}]'),/형식/);});

test('batch scheduler bounds parallel paid work and waits for in-flight requests after a failure',async()=>{const e=require('../public/upload-engine');let active=0,max=0,started=[],finished=[];await assert.rejects(e.runBatches([0,1,2,3],async(x)=>{started.push(x);max=Math.max(max,++active);await new Promise(r=>setTimeout(r,x===0?1:10));active--;finished.push(x);if(x===0)throw Error('invalid JSON');}),/invalid JSON/);assert.equal(max,2);assert.deepEqual(started,[0,1]);assert.equal(active,0);assert.equal(finished.length,2);});

function pdfSetup(){const nodes={status:{},source:{value:''}},ocr=[];const texts=['보험 상품의 가입 조건과 지급 조건은 약관에서 확인합니다. 3.10.5','౸ݒਭਊ'.repeat(20),''];const c=vm.createContext({UploadEngine:require('../public/upload-engine'),document:{getElementById:id=>nodes[id],createElement:()=>({getContext:()=>({}),toDataURL:()=> 'data:image/jpeg;base64,page'})},pdfjsLib:{getDocument:()=>({promise:Promise.resolve({numPages:3,getPage:async p=>({getTextContent:async()=>({items:[{str:texts[p-1],hasEOL:true}]}),getViewport:()=>({width:100,height:100}),render:()=>({promise:Promise.resolve()})})})})},extractTextFromImageBase64:async()=>{ocr.push(1);return '이미지 원문에서 확인한 지급 조건';}});const a=html.indexOf('async function handlePdfUpload'),b=html.indexOf("document.getElementById('genBtn').addEventListener",a);vm.runInContext(html.slice(a,b),c);return{c,nodes,ocr};}
test('actual PDF path keeps readable text free and OCRs corrupt or empty pages',async()=>{const h=pdfSetup();await h.c.handlePdfUpload({name:'test.pdf',arrayBuffer:async()=>new ArrayBuffer(0)},'status','source',()=>{});assert.equal(h.ocr.length,2);assert.match(h.nodes.source.value,/3.10.5/);assert.ok(!h.nodes.source.value.includes('౸'));assert.match(h.nodes.source.value,/p.3 - 이미지 인식/);});
test('free-only PDF upload does not pay for missing pages and shows explicit omissions',async()=>{const h=pdfSetup();await h.c.handlePdfUpload({name:'test.pdf',arrayBuffer:async()=>new ArrayBuffer(0)},'status','source',()=>{},{skipOcr:true});assert.equal(h.ocr.length,0);assert.match(h.nodes.source.value,/분석에서 제외/);assert.match(h.nodes.source.value,/3.10.5/);});

test('short readable headings are retained even when the rest of a page needs image recognition',()=>{const e=require('../public/upload-engine');const q=e.inspectText('가입 조건 3.10.5');assert.equal(q.needsOcr,true);assert.equal(q.partialReadable,true);assert.equal(q.cleaned,'가입 조건 3.10.5');const corrupt=e.inspectText('౸ݒਭਊ'.repeat(20));assert.equal(corrupt.partialReadable,false);});
